name: orange_eye_foss2
description: OrangeEye is a web monitor and API REST client for Android(23) 6+ made in pure Flutter.

version: 1.0.0+3

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  background_fetch: ^1.1.5
  easy_dynamic_theme: ^2.2.0
  flutter_localizations:
    sdk: flutter
  yaml: 3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  connectivity: ^3.0.6
  intl: ^0.17.0
  url_launcher: ^6.0.4
  shared_preferences: 2.0.8
  about: ^2.1.0
  keyboard_dismisser: ^2.0.0
  flutter_share: ^2.0.0
  expansion_tile_card: ^2.0.0
  rotated_corner_decoration: ^2.1.0+1
  flutter_local_notifications: ^11.0.1
  status_alert: ^1.0.0-nullsafety.1
  luhn: ^1.0.1
  disable_battery_optimization: ^1.1.0+1
  list_tile_switch: ^1.0.0
  file_picker: ^5.2.9
  permission_handler: ^10.4.3
  auto_start_flutter: ^0.1.0
  external_path: ^1.0.3
  device_info_plus: ^4.1.2
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  remove_alpha_ios: true
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  assets:
    - lang/
    - assets/logo.png
    - assets/logo-dark.png
    - assets/icon.png
    - CHANGELOG.md
